/**
 * Simple translation system for the Roborock Queue Card.
 * Default language: Danish (da). Falls back to Danish for missing keys.
 */

const translations: Record<string, Record<string, string>> = {
  da: {
    // Status bar
    'status.battery': 'Batteri',
    'status.docked': 'Docket',
    'status.cleaning': 'Rengør',
    'status.returning': 'Returnerer',
    'status.charging': 'Oplader',
    'status.paused': 'Pauset',
    'status.error': 'Fejl',
    'status.idle': 'Klar',
    'status.room': 'Rum',
    'status.mop_attached': 'Moppe monteret',
    'status.mop_not_attached': 'Moppe ikke monteret',
    'status.running': 'Rengør',

    // Common
    'common.on': 'Til',
    'common.off': 'Fra',

    // Routines
    'routines.title': 'Rutiner',
    'routines.running': 'Kører',

    // Room grid
    'rooms.empty': 'Ingen rum tilgængelige',
    'rooms.cleaning': 'Rengør...',
    'rooms.done': 'Færdig',
    'rooms.ago_minutes': '{0}m siden',
    'rooms.ago_hours': '{0}t siden',
    'rooms.ago_days': '{0}d siden',
    'rooms.yesterday': 'I går',
    'rooms.today': 'I dag',

    // Queue panel
    'queue.title': 'Rengøringskø',
    'queue.default_mode': 'Standardtilstand for nye rum',
    'queue.empty': 'Tryk på rum for at tilføje til køen',
    'queue.start': 'Start rengøring',
    'queue.clear': 'Ryd valg',
    'queue.estimate_no_data': 'Ingen data endnu',
    'queue.estimate': 'Estimeret',
    'queue.last_run_title': 'Sidste rengøring',
    'queue.last_run_finished': 'Afsluttet kl.',
    'queue.estimate_minutes': 'ca. {0} min',

    // Modes
    'mode.vacuum': 'Støvsug',
    'mode.mop': 'Vask',
    'mode.deep': 'Dyb',

    // Queue controls (running)
    'controls.progress': 'Fremgang',
    'controls.pause': 'Pause',
    'controls.resume': 'Genoptag',
    'controls.skip': 'Spring over',
    'controls.cancel': 'Annuller',
    'controls.step': 'Trin',
    'controls.of': 'af',
    'controls.completed': 'Fuldført',
    'controls.in_progress': 'I gang',
    'controls.pending': 'Venter',
    'controls.skipped': 'Sprunget over',
    'controls.cleaning_in_progress': 'Rengøring i gang',

    // Maintenance
    'maintenance.title': 'Vedligeholdelse',
    'maintenance.reset': 'Nulstil',
    'maintenance.main_brush': 'Hovedbørste',
    'maintenance.side_brush': 'Sidebørste',
    'maintenance.filter': 'Filter',
    'maintenance.sensors': 'Sensorer',
    'maintenance.dock_strainer': 'Dock si',
    'maintenance.overdue': 'Udskiftning påkrævet!',
    'maintenance.hours_left': 'timer tilbage',
    'maintenance.mop_attached': 'Moppe monteret',
    'maintenance.water_shortage': 'Vandmangel',
    'maintenance.dirty_water': 'Beskidt vandbeholder',
    'maintenance.clean_water': 'Ren vandbeholder',
    'maintenance.child_lock': 'Børnesikring',
    'maintenance.dock_error': 'Dock fejl',
    'maintenance.mop_drying': 'Moppe tørring',
    'maintenance.total_cleanings': 'Rengøringer',
    'maintenance.total_area': 'Areal',
    'maintenance.total_time': 'Tid',

    // Dock diagnostics
    'dock.title': 'Dock',
    'dock.clean_water': 'Ren vandbeholder',
    'dock.dirty_water': 'Beskidt vandbeholder',
    'dock.error': 'Dock fejl',
    'dock.mop_drying': 'Moppe tørring',
    'dock.mop_drying_time': 'Tørretid',
    'dock.strainer': 'Dock si',
    'dock.ok': 'OK',
    'dock.problem': 'Problem',
    'dock.running': 'Kører',
    'dock.idle': 'Inaktiv',

    // Settings
    'settings.fan_speed': 'Sugestyrke',
    'settings.water_level': 'Vandmængde',
    'settings.quiet': 'Stille',
    'settings.balanced': 'Balanceret',
    'settings.turbo': 'Turbo',
    'settings.max': 'Max',
    'settings.low': 'Lav',
    'settings.medium': 'Medium',
    'settings.high': 'Høj',
    'settings.passes': 'Antal gange',

    // Pause reasons
    'pause_reason.user_paused': 'Sat på pause af bruger',
    'pause_reason.vacuum_error': 'Robotstøvsuger fejl',
    'pause_reason.retry_exhausted': 'Alle forsøg fejlede',
    'pause_reason.timeout': 'Timeout — robot svarede ikke',
    'pause_reason.unexpected_dock': 'Robot vendte uventet tilbage til dock',

    // Dock errors
    'dock_error.ok': 'OK',
    'dock_error.duct_blockage': 'Kanal blokeret',
    'dock_error.water_empty': 'Tomt for vand',
    'dock_error.waste_water_tank_full': 'Spildevandstank fuld',
    'dock_error.maintenance_brush_jammed': 'Vedligeholdelsesbørste sidder fast',
    'dock_error.dirty_tank_latch_open': 'Snavset tank-lås åben',
    'dock_error.no_dustbin': 'Ingen støvbeholder',
    'dock_error.cleaning_tank_full_or_blocked': 'Rengøringstank fuld eller blokeret',

    // Extended vacuum states
    'status.segment_cleaning': 'Støvsuger rum',
    'status.segment_mopping': 'Vasker rum',
    'status.segment_clean_mop_cleaning': 'Støvsuger rum (auto-vask)',
    'status.segment_clean_mop_mopping': 'Vasker rum (auto-vask)',
    'status.washing_the_mop': 'Vasker moppe',
    'status.washing_the_mop_2': 'Vasker moppe',
    'status.going_to_wash_the_mop': 'Kører til moppevask',
    'status.back_to_dock_washing_duster': 'Vasker moppe i dock',
    'status.returning_home': 'Kører hjem',
    'status.charging_complete': 'Fuldt opladet',
    'status.emptying_the_bin': 'Tømmer beholder',
    'status.starting': 'Starter',
    'status.spot_cleaning': 'Punktrengøring',
    'status.manual_mode': 'Manuel tilstand',
    'status.remote_control_active': 'Fjernstyring aktiv',
    'status.updating': 'Opdaterer',
    'status.docking': 'Docker',
    'status.going_to_target': 'Kører til mål',
    'status.zoned_cleaning': 'Zonerengøring',
    'status.zoned_mopping': 'Zonevask',
    'status.mapping': 'Kortlægger',
    'status.charging_problem': 'Opladningsproblem',
    'status.device_offline': 'Offline',
    'status.locked': 'Låst',
    'status.air_drying_stopping': 'Lufttørring stopper',
    'status.robot_status_mopping': 'Vasker',
    'status.clean_mop_cleaning': 'Støvsuger (auto-vask)',
    'status.clean_mop_mopping': 'Vasker (auto-vask)',
    'status.zoned_clean_mop_cleaning': 'Zonestøvsugning (auto-vask)',
    'status.zoned_clean_mop_mopping': 'Zonevask (auto-vask)',
    'status.attaching_the_mop': 'Monterer moppe',
    'status.detaching_the_mop': 'Afmonterer moppe',
    'status.unknown': 'Ukendt tilstand',

    // Diagnostics
    'diagnostics.title': 'Diagnostik',
    'diagnostics.loaded_rooms': 'Indlæste rum',
    'diagnostics.sensor_state': 'Sensor tilstand',
    'diagnostics.entity_check': 'Entiteter',
    'diagnostics.found': 'Fundet',
    'diagnostics.missing': 'Mangler',
    'diagnostics.segment_id': 'Segment',
    'diagnostics.queue_status': 'Kø status',
    'diagnostics.current_step': 'Nuværende trin',
    'diagnostics.pause_reason': 'Pause årsag',
  },
  en: {
    'status.battery': 'Battery',
    'status.docked': 'Docked',
    'status.cleaning': 'Cleaning',
    'status.returning': 'Returning',
    'status.charging': 'Charging',
    'status.paused': 'Paused',
    'status.error': 'Error',
    'status.idle': 'Ready',
    'status.room': 'Room',
    'status.mop_attached': 'Mop attached',
    'status.mop_not_attached': 'Mop not attached',
    'status.running': 'Cleaning',

    'common.on': 'On',
    'common.off': 'Off',

    'routines.title': 'Routines',
    'routines.running': 'Running',

    'rooms.empty': 'No rooms available',
    'rooms.cleaning': 'Cleaning...',
    'rooms.done': 'Done',
    'rooms.ago_minutes': '{0}m ago',
    'rooms.ago_hours': '{0}h ago',
    'rooms.ago_days': '{0}d ago',
    'rooms.yesterday': 'Yesterday',
    'rooms.today': 'Today',

    'queue.title': 'Cleaning Queue',
    'queue.default_mode': 'Default mode for new rooms',
    'queue.empty': 'Tap a room to add to queue',
    'queue.start': 'Start cleaning',
    'queue.clear': 'Clear selection',
    'queue.estimate_no_data': 'No data yet',
    'queue.estimate': 'Estimated',
    'queue.last_run_title': 'Last cleaning',
    'queue.last_run_finished': 'Finished at',
    'queue.estimate_minutes': 'approx. {0} min',

    'mode.vacuum': 'Vacuum',
    'mode.mop': 'Mop',
    'mode.deep': 'Deep',

    'controls.progress': 'Progress',
    'controls.pause': 'Pause',
    'controls.resume': 'Resume',
    'controls.skip': 'Skip',
    'controls.cancel': 'Cancel',
    'controls.step': 'Step',
    'controls.of': 'of',
    'controls.completed': 'Completed',
    'controls.in_progress': 'In progress',
    'controls.pending': 'Pending',
    'controls.skipped': 'Skipped',
    'controls.cleaning_in_progress': 'Cleaning in progress',

    'maintenance.title': 'Maintenance',
    'maintenance.reset': 'Reset',
    'maintenance.main_brush': 'Main brush',
    'maintenance.side_brush': 'Side brush',
    'maintenance.filter': 'Filter',
    'maintenance.sensors': 'Sensors',
    'maintenance.dock_strainer': 'Dock strainer',
    'maintenance.overdue': 'Replacement needed!',
    'maintenance.hours_left': 'hours left',
    'maintenance.mop_attached': 'Mop attached',
    'maintenance.water_shortage': 'Water shortage',
    'maintenance.dirty_water': 'Dirty water box',
    'maintenance.clean_water': 'Clean water box',
    'maintenance.child_lock': 'Child lock',
    'maintenance.dock_error': 'Dock error',
    'maintenance.mop_drying': 'Mop drying',
    'maintenance.total_cleanings': 'Cleanings',
    'maintenance.total_area': 'Area',
    'maintenance.total_time': 'Time',

    'dock.title': 'Dock',
    'dock.clean_water': 'Clean water box',
    'dock.dirty_water': 'Dirty water box',
    'dock.error': 'Dock error',
    'dock.mop_drying': 'Mop drying',
    'dock.mop_drying_time': 'Drying time',
    'dock.strainer': 'Dock strainer',
    'dock.ok': 'OK',
    'dock.problem': 'Problem',
    'dock.running': 'Running',
    'dock.idle': 'Idle',

    // Settings
    'settings.fan_speed': 'Fan speed',
    'settings.water_level': 'Water level',
    'settings.quiet': 'Quiet',
    'settings.balanced': 'Balanced',
    'settings.turbo': 'Turbo',
    'settings.max': 'Max',
    'settings.low': 'Low',
    'settings.medium': 'Medium',
    'settings.high': 'High',
    'settings.passes': 'Passes',

    // Pause reasons
    'pause_reason.user_paused': 'Paused by user',
    'pause_reason.vacuum_error': 'Vacuum error',
    'pause_reason.retry_exhausted': 'All retry attempts failed',
    'pause_reason.timeout': 'Timeout — robot not responding',
    'pause_reason.unexpected_dock': 'Robot unexpectedly returned to dock',

    // Dock errors
    'dock_error.ok': 'OK',
    'dock_error.duct_blockage': 'Duct blockage',
    'dock_error.water_empty': 'Water empty',
    'dock_error.waste_water_tank_full': 'Waste water tank full',
    'dock_error.maintenance_brush_jammed': 'Maintenance brush jammed',
    'dock_error.dirty_tank_latch_open': 'Dirty tank latch open',
    'dock_error.no_dustbin': 'No dustbin',
    'dock_error.cleaning_tank_full_or_blocked': 'Cleaning tank full or blocked',

    // Extended vacuum states
    'status.segment_cleaning': 'Vacuuming room',
    'status.segment_mopping': 'Mopping room',
    'status.segment_clean_mop_cleaning': 'Vacuuming room (auto-wash)',
    'status.segment_clean_mop_mopping': 'Mopping room (auto-wash)',
    'status.washing_the_mop': 'Washing mop',
    'status.washing_the_mop_2': 'Washing mop',
    'status.going_to_wash_the_mop': 'Going to wash mop',
    'status.back_to_dock_washing_duster': 'Washing mop at dock',
    'status.returning_home': 'Returning home',
    'status.charging_complete': 'Fully charged',
    'status.emptying_the_bin': 'Emptying bin',
    'status.starting': 'Starting',
    'status.spot_cleaning': 'Spot cleaning',
    'status.manual_mode': 'Manual mode',
    'status.remote_control_active': 'Remote control active',
    'status.updating': 'Updating',
    'status.docking': 'Docking',
    'status.going_to_target': 'Going to target',
    'status.zoned_cleaning': 'Zone cleaning',
    'status.zoned_mopping': 'Zone mopping',
    'status.mapping': 'Mapping',
    'status.charging_problem': 'Charging problem',
    'status.device_offline': 'Offline',
    'status.locked': 'Locked',
    'status.air_drying_stopping': 'Air drying stopping',
    'status.robot_status_mopping': 'Mopping',
    'status.clean_mop_cleaning': 'Vacuuming (auto-wash)',
    'status.clean_mop_mopping': 'Mopping (auto-wash)',
    'status.zoned_clean_mop_cleaning': 'Zone vacuuming (auto-wash)',
    'status.zoned_clean_mop_mopping': 'Zone mopping (auto-wash)',
    'status.attaching_the_mop': 'Attaching mop',
    'status.detaching_the_mop': 'Detaching mop',
    'status.unknown': 'Unknown state',

    // Diagnostics
    'diagnostics.title': 'Diagnostics',
    'diagnostics.loaded_rooms': 'Loaded rooms',
    'diagnostics.sensor_state': 'Sensor state',
    'diagnostics.entity_check': 'Entities',
    'diagnostics.found': 'Found',
    'diagnostics.missing': 'Missing',
    'diagnostics.segment_id': 'Segment',
    'diagnostics.queue_status': 'Queue status',
    'diagnostics.current_step': 'Current step',
    'diagnostics.pause_reason': 'Pause reason',
  },
};

let _currentLang = 'da';

export function setLanguage(lang: string): void {
  _currentLang = translations[lang] ? lang : 'da';
}

export function t(key: string): string {
  return translations[_currentLang]?.[key]
    ?? translations['da']?.[key]
    ?? key;
}
